replicaCount: 1

image:
  repository: 143694936311.dkr.ecr.us-west-2.amazonaws.com/demo-prod
  tag: prod

config:
  envName: "prod"
  emailSupport: "Demo Support <demo@arus.io>"
  emailFrom: "Demo <demo@arus.io>"
  siteDomain: "arus.io"
  sentryEnvironment: "prod"
  adminTwoFactor: "true"

secrets:
  databaseUrl: "postgres://demo:XULu2ocjhqr3P9@demo-prod-db.cqid93hpab9n.us-west-2.rds.amazonaws.com:5432/demo"
  sendgridApiKey: "123"
  secretToken: "1Ny7ue7EZYKzjQAtDJLvAJ8zYL6KkQpsjZHZyabZ"
  twilioAuthToken: "123"

resources:
  requests:
    cpu: 100m
    memory: 512Mi


ingress:
  enabled: true
  hosts:
  - "*.arus.io"
  path: /*
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:143694936311:certificate/1fa07cf0-41f1-4ba6-bb31-089858553d7b
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    #alb.ingress.kubernetes.io/security-groups: sg-03b99f53927bb0443
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/tags: Environment=prod,Project=Arus,Name=demo
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=14400
    # the next attributes are required for soc2 - but I had to apply them manually (on an existing ingress)
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.drop_invalid_header_fields.enabled=true,access_logs.s3.enabled=true,access_logs.s3.bucket=eks-ingress-access-log,deletion_protection.enabled=true
    kubernetes.io/ingress.class: alb
