version: '3'
services:
  db:
    container_name: demo-db
    image: postgres:12.1
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'boilerplate'
      POSTGRES_USER: 'boilerplate'
      POSTGRES_DB: 'boilerplate'

  adminer:
    container_name: demo-adminer
    image: adminer
    restart: always
    ports:
      - 8199:8080

  redis:
    container_name: demo-redis
    image: redis:5.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
