version: '3'
services:
  db:
    container_name: backend-db
    image: postgres:11.5
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'boilerplate'
      POSTGRES_USER: 'boilerplate'
      POSTGRES_DB: 'boilerplate'

  adminer:
    container_name: backend-adminer
    image: adminer
    restart: always
    ports:
      - 8199:8080

  redis:
    image: redis:5.0.5-alpine
    container_name: ourtitl-redis
    restart: always
    ports:
      - '6379:6379'
