apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}-api
  labels:
    app: {{ include "demo.name" . }}-api
    chart: {{ include "demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: express
      protocol: TCP
      name: express
  selector:
    app: {{ include "demo.name" . }}-api
    release: {{ .Release.Name }}
