apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "backend.fullname" . }}-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- with .Values.config }}
data:
  ENV_NAME: {{ .envName | quote }}
  S3_BUCKET: {{ .s3Bucket | quote }}
  S3_REGION: {{ .s3Region | quote }}
  S3_ACCESS_KEY: {{ .s3AccessKey | quote }}
  EMAIL_SUPPORT: {{ .emailSupport | quote }}
  EMAIL_FROM: {{ .emailFrom | quote }}
  EMAIL_WHITELIST: {{ .emailWhitelist | quote }}
  SITE_DOMAIN: {{ .siteDomain | quote }}
  SMS_CLIENT: {{ .smsClient | quote }}
  TWILIO_ACCOUNT_SID: {{ .twilioAccountSid | quote }}
  DOCS_CLIENT: {{ .docsClient | quote }}
  GDRIVE_OUTPUT_FOLDER: {{ .gdriveOutputFolder | quote }}
  SENTRY_ENVIRONMENT: {{ .sentryEnvironment | quote }}
  SERVER_SENTRY_DSN: {{ .sentryServerDsn | quote }}
  ADMIN_TWO_FACTOR: {{ .adminTwoFactor | quote }}
{{- end -}}
