{{- range .Values.jobs }}
---
apiVersion: batch/v1beta1
kind:  CronJob
metadata:
  name: {{ include "demo.fullname" $ }}-{{ .name }}
  labels:
    app: {{ include "demo.name" $ }}-{{ .name }}
    chart: {{ include "demo.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum }}
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ $.Chart.Name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
              {{- range .command }}
                - {{ . }}
              {{- end }}
              env:
              - name: SENTRY_COMPONENT
                value: {{ .name }}
              envFrom:
              - configMapRef:
                  name: {{ template "demo.fullname" $ }}-config
              - secretRef:
                  name: {{ template "demo.fullname" $ }}-secrets
{{- end }}
