apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "demo.fullname" . }}-migrations
  labels:
    app: {{ include "demo.name" . }}-migrations
    chart: {{ include "demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum }}
      labels:
        app: {{ include "demo.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ $.Chart.Name }}-migrations
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ['npm', 'run', 'postinstall']
          env:
          - name: SENTRY_COMPONENT
            value: migration
          envFrom:
          - configMapRef:
              name: {{ template "demo.fullname" $ }}-config
          - secretRef:
              name: {{ template "demo.fullname" $ }}-secrets
