apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.name" . }}-redis
  labels:
    app: {{ include "demo.name" . }}-redis
    chart: {{ include "demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.redisService.type }}
  ports:
    - port: {{ .Values.redisService.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app: {{ include "demo.name" . }}-redis
    release: {{ .Release.Name }}
