apiVersion: v1
kind: Secret
metadata:
  name: {{ template "demo.fullname" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- with .Values.secrets }}
data:
  SENDGRID_API_KEY: {{ .sendgridApiKey | b64enc }}
  DATABASE_URL: {{ .databaseUrl | b64enc }}
  REDIS_URL: {{ .redisUrl | b64enc }}
  SECRET_TOKEN: {{ .secretToken | b64enc }}
  TWILIO_AUTH_TOKEN: {{ .twilioAuthToken | b64enc }}
{{- end -}}
